const express = require('express');
const controller = require('../controllers/compras.controller');
const proyectosController = require('../controllers/compras-proyectos.controller');
const placasController = require('../controllers/compras-placas.controller');
const comprasDiccionarioController = require('../controllers/compras-diccionario-test');
const comprasJsonController = require('../controllers/compras-json-test');
const comprasDosConsultasController = require('../controllers/compras-dos-consultas-test');
const comprasPingController = require('../controllers/compras-ping-test');
const comprasLotesController = require('../controllers/compras-lotes-test');
const comprasSinOrderController = require('../controllers/compras-sin-order-test');
const comprasSoloController = require('../controllers/compras-solo-test');
const { requireSession } = require('../auth/session');
const router = express.Router();
router.get('/compras',requireSession,controller.compras);
router.get('/compras/proyectos',requireSession,proyectosController.resumenGastosPorProyecto);
router.get('/compras/vehiculos',requireSession,proyectosController.resumenGastosPorVehiculo);
router.get('/compras/reporte-area',requireSession,proyectosController.reporteDetallePorArea);
router.get('/compras/reporte-area/pdf',requireSession,proyectosController.exportarReporteAreaPdf);
router.get('/compras/placas',requireSession,placasController.listarPlacas);
router.get('/compras/reporte-placa',requireSession,placasController.reporteDetallePorPlaca);
router.get('/compras/reporte-placa/pdf',requireSession,placasController.exportarReportePlacaPdf);
router.get('/compras-solo-test',requireSession,comprasSoloController.comprasSoloTest);router.get('/compras-diccionario-test',requireSession,comprasDiccionarioController.comprasDiccionarioTest);router.get('/compras-conexion-test',requireSession,comprasDiccionarioController.comprasConexionTest);router.get('/compras-json-test',requireSession,comprasJsonController.comprasJsonTest);router.get('/compras-dos-consultas-test',requireSession,comprasDosConsultasController.comprasDosConsultasTest);router.get('/compras-ping-test',requireSession,comprasPingController.comprasPingTest);router.get('/compras-lotes-test',requireSession,comprasLotesController.comprasLotesTest);router.get('/compras-sin-order-test',requireSession,comprasSinOrderController.comprasSinOrderTest);
module.exports=router;
